#!/bin/bash

##############################################
# DhakaCart Full Stack Deployment Automation
# Complete infrastructure to production in one script
#
# 🇧🇩 এই স্ক্রিপ্ট সম্পূর্ণ প্রোজেক্ট ডিপ্লয় করবে (Infrastructure + K8s + App)
# 🇺🇸 This script automates the full deployment (Infrastructure + K8s + App)
##############################################

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
STATE_FILE="$SCRIPT_DIR/.deploy_state"

# Check for force flag
FORCE=false
if [[ "$1" == "--force" ]]; then
    FORCE=true
fi

if [ "$FORCE" = true ]; then
    echo -e "${YELLOW}Force mode enabled. Resetting deployment state...${NC}"
    rm -f "$STATE_FILE"
fi

# Load last step
LAST_STEP=0
if [ -f "$STATE_FILE" ]; then
    LAST_STEP=$(cat "$STATE_FILE")
fi

# Helper function to save progress state
# 🇧🇩 এই ফাংশনটি আমাদের জানিয়ে দেয় আমরা কোন স্টেপে আছি, যাতে স্ক্রিপ্ট বন্ধ হলে সেখান থেকে শুরু করা যায় (State Management)
update_state() {
    echo "$1" > "$STATE_FILE"
}

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  DhakaCart Full Stack Deployment${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "⏱️  Target: Complete deployment in <4 hours"
echo "📍 Starting at: $(date '+%H:%M:%S')"
if [ "$LAST_STEP" -gt 0 ]; then
    echo "🔄 Resuming from Step $((LAST_STEP + 1))..."
fi
echo ""

# Step 1: Infrastructure (Terraform)
# 🇧🇩 ধাপ ১: ইনফ্রাস্ট্রাকচার তৈরি করা (VPC, EC2, Load Balancer)
# 🇺🇸 Step 1: Provision Infrastructure (VPC, EC2, Load Balancer) using Terraform
if [ "$LAST_STEP" -ge 1 ]; then
    echo -e "${GREEN}✅ [1/7] Infrastructure already deployed. Skipping...${NC}"
else
    echo -e "${YELLOW}[1/7] 🏗️  Deploying Infrastructure with Terraform...${NC}"
    cd "$PROJECT_ROOT/terraform/aws-infra"
    
    # Check removed: Key is generated by Terraform in the next step
    # if [ ! -f "dhakacart-k8s-key.pem" ]; then
    #     echo -e "${RED}❌ SSH key not found!${NC}"
    #     exit 1
    # fi
    
    terraform init -upgrade
    terraform apply -auto-approve
    
    echo -e "${GREEN}✅ Infrastructure deployed${NC}"
    update_state 1
    echo ""
fi

# Step 2: Extract configuration
# 🇧🇩 ধাপ ২: আইপি অ্যাড্রেস এবং ডিএনএস খুঁজে বের করা (যা Terraform আউটপুট দিয়েছে)
# 🇺🇸 Step 2: Extract IPs and DNS from Terraform output
if [ "$LAST_STEP" -ge 2 ]; then
    echo -e "${GREEN}✅ [2/7] Configuration already extracted. Skipping...${NC}"
    # We still need to load variables for subsequent steps
    source "$PROJECT_ROOT/scripts/load-env.sh" > /dev/null
else
    echo -e "${YELLOW}[2/7] 📋 Extracting configuration...${NC}"
    source "$PROJECT_ROOT/scripts/load-env.sh"
    
    echo "  Bastion IP: $BASTION_IP"
    echo "  Master-1 IP: ${MASTER_IPS[0]}"
    echo "  ALB DNS: $ALB_DNS"
    echo -e "${GREEN}✅ Configuration loaded${NC}"
    update_state 2
    echo ""
fi

# Ensure variables are loaded if we skipped step 2
if [ -z "$BASTION_IP" ]; then
    source "$PROJECT_ROOT/scripts/load-env.sh" > /dev/null
fi

# Step 3: Update node configuration scripts
# 🇧🇩 ধাপ ৩: সার্ভার কনফিগ করার জন্য স্ক্রিপ্ট জেনারেট করা (IP বসানো)
# 🇺🇸 Step 3: Generate node configuration scripts with dynamic IPs
if [ "$LAST_STEP" -ge 3 ]; then
    echo -e "${GREEN}✅ [3/7] Node configuration scripts already updated. Skipping...${NC}"
else
    echo -e "${YELLOW}[3/7] 📝 Updating node configuration scripts...${NC}"
    cd "$PROJECT_ROOT/scripts/provisioning"
    ./extract-terraform-outputs.sh
    ./generate-node-scripts.sh
    echo -e "${GREEN}✅ Scripts generated${NC}"
    update_state 3
    echo ""
fi

# Step 4: Upload to Bastion, Propagate, and Configure Nodes
# 🇧🇩 ধাপ ৪: স্ক্রিপ্টগুলো Bastion এ আপলোড করা এবং সব নোডে পাঠিয়ে দেয়া
# 🇺🇸 Step 4: Upload scripts to Bastion and propagate to all internal nodes
if [ "$LAST_STEP" -ge 4 ]; then
     echo -e "${GREEN}✅ [4/7] Kubernetes nodes already configured (Upload & Hostnames). Skipping...${NC}"
     else
         echo -e "${YELLOW}[4/7] 🚀 Configuring Kubernetes nodes (Upload & Propagate)...${NC}"
             # Step 4.0: Upload to Bastion
                 "$PROJECT_ROOT/scripts/provisioning/upload-to-bastion.sh"

                         # Upload prereq templates to Bastion (needed for automated join)
                             echo -e "${YELLOW}📤 Uploading prereq templates to Bastion...${NC}"
                                 scp -i "$SSH_KEY_PATH" "$PROJECT_ROOT/scripts/provisioning/templates/master-2-prereq.sh" ubuntu@${BASTION_IP}:~/nodes-config/
                                     scp -i "$SSH_KEY_PATH" "$PROJECT_ROOT/scripts/provisioning/templates/workers-prereq.sh" ubuntu@${BASTION_IP}:~/nodes-config/

                                             # Propagate scripts from Bastion to Internal Nodes
                                                 echo -e "${YELLOW}🚀 Propagating scripts to internal nodes...${NC}"

                                                         # Master-1
                                                             ssh -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no ubuntu@${BASTION_IP} \
                                                                   "scp -i ~/.ssh/dhakacart-k8s-key.pem -o StrictHostKeyChecking=no ~/nodes-config/master-1.sh ubuntu@${MASTER_IPS[0]}:~/"

                                                                           # Master-2
                                                                               if [ ${#MASTER_IPS[@]} -gt 1 ]; then
                                                                                   ssh -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no ubuntu@${BASTION_IP} \
                                                                                         "scp -i ~/.ssh/dhakacart-k8s-key.pem -o StrictHostKeyChecking=no ~/nodes-config/master-2-prereq.sh ubuntu@${MASTER_IPS[1]}:~/"
                                                                                             fi

                                                                                                     # Workers
                                                                                                         for worker_ip in "${WORKER_IPS[@]}"; do
                                                                                                             ssh -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no ubuntu@${BASTION_IP} \
                                                                                                                   "scp -i ~/.ssh/dhakacart-k8s-key.pem -o StrictHostKeyChecking=no ~/nodes-config/workers-prereq.sh ubuntu@$worker_ip:~/"
                                                                                                                       done

                                                                                                                               echo -e "${GREEN}✅ Scripts propagated${NC}"

                                                                                                                                       echo "⏳ Waiting 30s for Bastion readiness..."
                                                                                                                                           sleep 30
                                                                                                                                               
    # Step 4.1: Change Hostnames
    # 🇧🇩 সব নোডের নাম (Hostname) ঠিক করা (যেমন: master-1, worker-1)
    # 🇺🇸 Set correct hostnames for all nodes
    echo -e "${YELLOW}[4.1/7] 🏷️  Updating Hostnames...${NC}"
    bash "$PROJECT_ROOT/scripts/utils/hostname/change-hostname-via-bastion.sh" --all --yes
    echo -e "${GREEN}✅ Hostnames updated${NC}"
    
    update_state 4
    echo ""
fi


# Step 5: Configure Master-1 and Join Nodes
# 🇧🇩 ধাপ ৫: কুবারনেটিস ক্লাস্টার তৈরি করা এবং বাকি নোডগুলোকে জয়েন করানো
# 🇺🇸 Step 5: Initialize K8s cluster and join all nodes
if [ "$LAST_STEP" -ge 5 ]; then
    echo -e "${GREEN}✅ [5/7] Cluster initialized and nodes joined. Skipping...${NC}"
else
    echo -e "${YELLOW}[5/7] 🔧 Initializing Cluster...${NC}"
    
    # Configure Master-1
    echo "  Configuring Master-1..."
    ssh -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem -o StrictHostKeyChecking=no ubuntu@${MASTER_IPS[0]} \
       'bash ~/master-1.sh'" &
    
    MASTER1_PID=$!
    echo "  Master-1 configuration started (PID: $MASTER1_PID)"
    
    # Wait for Master-1 to complete
    wait $MASTER1_PID
    if [ $? -eq 0 ]; then
         echo -e "${GREEN}✅ Master-1 configured${NC}"
    else
         echo -e "${RED}❌ Master-1 configuration failed!${NC}"
         exit 1
    fi
    
    # Get join tokens
    echo "  Extracting join tokens..."
    
    # Join command for control plane (Master-2)
    # Re-upload certs to get a fresh key (needed because previous key might be known or lost)
    CERT_KEY=$(ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@${MASTER_IPS[0]} \
       'sudo kubeadm init phase upload-certs --upload-certs 2>/dev/null | tail -1'")

    CP_JOIN_COMMAND=$(ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@${MASTER_IPS[0]} \
       'kubeadm token create --print-join-command --certificate-key $CERT_KEY'")
    
    # Join command for workers
    WORKER_JOIN_COMMAND=$(ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@${MASTER_IPS[0]} \
       'kubeadm token create --print-join-command'")
    
    # Join Master-2 to control plane
    if [ ${#MASTER_IPS[@]} -gt 1 ]; then
        echo "  Joining Master-2 to control plane..."
        ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
          "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@${MASTER_IPS[1]} \
           'bash ~/master-2-prereq.sh && sudo $CP_JOIN_COMMAND --control-plane'" &
        MASTER2_PID=$!
        wait $MASTER2_PID
        echo -e "${GREEN}✅ Master-2 joined${NC}"
    fi
    
    # Join Workers in parallel
    echo "  Joining ${#WORKER_IPS[@]} Worker nodes..."
    for worker_ip in "${WORKER_IPS[@]}"; do
        echo "    Joining worker: $worker_ip"
        ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
          "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@$worker_ip \
           'bash ~/workers-prereq.sh && sudo $WORKER_JOIN_COMMAND'" &
    done
    
    wait
    echo -e "${GREEN}✅ All ${#WORKER_IPS[@]} workers joined${NC}"
    update_state 5
    echo ""
fi

# Step 6: Deploy Application
# 🇧🇩 ধাপ ৬: ঢাকা কার্ট অ্যাপ ও ডাটাবেস ডিপ্লয় করা
# 🇺🇸 Step 6: Deploy DhakaCart App, DB, and Redis
if [ "$LAST_STEP" -ge 6 ]; then
    echo -e "${GREEN}✅ [6/7] Application already deployed. Skipping...${NC}"
else
    echo -e "${YELLOW}[6/7] 📦 Deploying Application...${NC}"
    cd "$PROJECT_ROOT"
    
    # Update ConfigMap with ALB DNS
    sed -i "s|REACT_APP_API_URL:.*|REACT_APP_API_URL: http://${ALB_DNS}/api|" k8s/configmaps/app-config.yaml
    
    # Sync to Master-1
    ./scripts/k8s-deployment/sync-k8s-to-master1.sh
    
    # Deploy
    ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@${MASTER_IPS[0]} \
       'cd ~/k8s && chmod +x ./apply-manifests.sh && ./apply-manifests.sh'"
    
    echo -e "${GREEN}✅ Application deployed${NC}"
    update_state 6
    echo ""
fi

# Step 6.1: Seed Database
# 🇧🇩 ধাপ ৬.১: ডাটাবেসে স্যাম্পল ডাটা (Products, Users) ঢুকানো
# 🇺🇸 Step 6.1: Populate database with initial data
if [ "$LAST_STEP" -ge 61 ]; then
    echo -e "${GREEN}✅ [6.1/7] Database already seeded. Skipping...${NC}"
else
    echo -e "${YELLOW}[6.1/7] 🌱 Seeding Database...${NC}"
    "$PROJECT_ROOT/scripts/database/seed-database.sh" --automated
    
    echo -e "${GREEN}✅ Database seeding initiated${NC}"
    update_state 61
    echo ""
fi

# Step 7: Register ALB Targets & Verification
# 🇧🇩 ধাপ ৭: লোড ব্যালেন্সারের সাথে ওয়ার্কার নোড কানেক্ট করা
# 🇺🇸 Step 7: Register Worker nodes to ALB Target Group
if [ "$LAST_STEP" -ge 7 ]; then
    echo -e "${GREEN}✅ [7/7] ALB targets registered and verified. Skipping...${NC}"
else
    echo -e "${YELLOW}[7/7] 🎯 Registering ALB targets & Verifying...${NC}"
    cd "$PROJECT_ROOT/terraform/aws-infra"
    ./register-workers-to-alb.sh
    
    echo -e "${GREEN}✅ ALB targets registered${NC}"
    
    echo "⏳ Waiting for pods to be ready (60s)..."
    sleep 60
    
    ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem ubuntu@${MASTER_IPS[0]} \
       'kubectl get nodes && kubectl get pods -n dhakacart && kubectl get pods -n monitoring'"
    
    update_state 7
fi

# Step 8: Enterprise Features (Phase 8)
# 🇧🇩 ধাপ ৮: এনটারপ্রাইজ ও সিকিউরিটি ফিচার সেটআপ (Velero, Vault, HTTPS)
# 🇺🇸 Step 8: Install Enterprise Features (Backup, Secrets, SSL)
if [ "$LAST_STEP" -ge 8 ]; then
    echo -e "${GREEN}✅ [8/8] Enterprise features already deployed. Skipping...${NC}"
else
    echo -e "${YELLOW}[8/8] 🛡️  Deploying Enterprise Features (Velero, Vault, Cert-Manager)...${NC}"
    
    # Run installation scripts on Master-1
    ssh -i "$SSH_KEY_PATH" ubuntu@${BASTION_IP} \
      "ssh -i ~/.ssh/dhakacart-k8s-key.pem -o StrictHostKeyChecking=no ubuntu@${MASTER_IPS[0]} \
       'cd ~/scripts/enterprise-features && \
        chmod +x *.sh && \
        echo \"Installing Velero...\" && ./install-velero.sh && \
        echo \"Installing Cert-Manager...\" && ./install-cert-manager.sh && \
        echo \"Installing Vault...\" && ./install-vault.sh'"
    
    echo -e "${GREEN}✅ Enterprise features deployed${NC}"
    update_state 8
    echo ""
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  ✅ Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "⏱️  Completed at: $(date '+%H:%M:%S')"
echo ""
echo -e "${BLUE}🌐 Access URLs:${NC}"
echo "  Frontend: http://${ALB_DNS}"
echo "  Grafana:  http://${ALB_DNS}/grafana/"
echo "  Login:    admin / dhakacart123"
echo ""
echo -e "${YELLOW}💡 Manual Verification Needed:${NC}"
echo "  1. Test frontend: curl -I http://${ALB_DNS}"
echo "  2. Access Grafana: http://${ALB_DNS}/grafana/ (User: admin / Pass: dhakacart123)"
echo "  3. Import Grafana Dashboard: ID 1860 (Node Exporter Full)"
echo "  4. Check Logs: kubectl logs -n monitoring daemonset/promtail"
echo "  5. Run Security Hardening: ./scripts/security/apply-security-hardening.sh"
echo "  6. Verify DB: ./scripts/utils/database/diagnose-db-products-issue.sh"
echo ""
echo ""
echo -e "${BLUE}📄 Documentation Reference:${NC}"
echo "  - deployment: FULL-DEPLOYMENT-GUIDE.md"
echo "  - verification: QUICK-REFERENCE.md"
echo ""
