#!/bin/bash
# SSL/TLS Certificate Setup using Let's Encrypt (Certbot)
# Automates SSL certificate generation and renewal

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   SSL/TLS Certificate Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Please run as root (sudo)${NC}"
    exit 1
fi

# Check if certbot is installed
if ! command -v certbot &> /dev/null; then
    echo -e "${YELLOW}Certbot not found. Installing...${NC}"
    
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
    else
        echo -e "${RED}Please install certbot manually${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Certbot installed${NC}"
fi

# Get domain information
echo -e "${YELLOW}Domain Configuration:${NC}"
read -p "Enter your domain name (e.g., dhakacart.com): " DOMAIN
read -p "Enter www subdomain? (y/n): " INCLUDE_WWW
read -p "Enter api subdomain? (y/n): " INCLUDE_API
read -p "Enter your email for certificate notifications: " EMAIL

# Build domain list
DOMAINS="-d $DOMAIN"
[ "$INCLUDE_WWW" = "y" ] && DOMAINS="$DOMAINS -d www.$DOMAIN"
[ "$INCLUDE_API" = "y" ] && DOMAINS="$DOMAINS -d api.$DOMAIN"

echo ""
echo -e "${YELLOW}Certificate will be issued for:${NC}"
echo "$DOMAINS" | tr ' ' '\n' | grep "^-d" | sed 's/-d /  - /'
echo ""

read -p "Continue? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ]; then
    echo "Cancelled."
    exit 0
fi

# Check if nginx is installed
if ! command -v nginx &> /dev/null; then
    echo -e "${YELLOW}Nginx not found. Installing...${NC}"
    apt-get install -y nginx
    systemctl start nginx
    systemctl enable nginx
    echo -e "${GREEN}✓ Nginx installed${NC}"
fi

# Obtain certificate
echo ""
echo -e "${YELLOW}Obtaining SSL certificate...${NC}"
certbot certonly \
    --nginx \
    $DOMAINS \
    --email "$EMAIL" \
    --agree-tos \
    --no-eff-email \
    --redirect

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Certificate obtained successfully${NC}"
else
    echo -e "${RED}Failed to obtain certificate${NC}"
    exit 1
fi

# Set up auto-renewal
echo ""
echo -e "${YELLOW}Setting up automatic renewal...${NC}"

# Create renewal script
cat > /usr/local/bin/renew-dhakacart-certs.sh <<'EOF'
#!/bin/bash
# Auto-renewal script for DhakaCart SSL certificates

certbot renew --quiet --nginx

# Reload nginx if renewal was successful
if [ $? -eq 0 ]; then
    systemctl reload nginx
    echo "$(date): Certificates renewed successfully" >> /var/log/cert-renewal.log
fi
EOF

chmod +x /usr/local/bin/renew-dhakacart-certs.sh

# Add to crontab (run twice daily as recommended)
CRON_JOB="0 0,12 * * * /usr/local/bin/renew-dhakacart-certs.sh"
(crontab -l 2>/dev/null | grep -v "renew-dhakacart-certs"; echo "$CRON_JOB") | crontab -

echo -e "${GREEN}✓ Auto-renewal configured${NC}"

# Create nginx SSL configuration
echo ""
echo -e "${YELLOW}Creating nginx SSL configuration...${NC}"

SSL_CONF="/etc/nginx/sites-available/dhakacart-ssl"
cat > "$SSL_CONF" <<EOF
# DhakaCart SSL Configuration
# Generated by certbot-setup.sh on $(date)

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN $([ "$INCLUDE_WWW" = "y" ] && echo "www.$DOMAIN");
    
    # Redirect HTTP to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN $([ "$INCLUDE_WWW" = "y" ] && echo "www.$DOMAIN");
    
    # SSL Certificate
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/$DOMAIN/chain.pem;
    
    # SSL Configuration (Mozilla Intermediate)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;
    
    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Frontend
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
    
    # Backend API
    location /api {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

if [ "$INCLUDE_API" = "y" ]; then
    cat >> "$SSL_CONF" <<EOF

# API Subdomain
server {
    listen 80;
    listen [::]:80;
    server_name api.$DOMAIN;
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name api.$DOMAIN;
    
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/$DOMAIN/chain.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    
    add_header Strict-Transport-Security "max-age=31536000" always;
    
    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
fi

# Enable site
ln -sf "$SSL_CONF" /etc/nginx/sites-enabled/dhakacart-ssl

# Test nginx configuration
echo -e "${YELLOW}Testing nginx configuration...${NC}"
nginx -t

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Nginx configuration valid${NC}"
    systemctl reload nginx
    echo -e "${GREEN}✓ Nginx reloaded${NC}"
else
    echo -e "${RED}Nginx configuration error${NC}"
    exit 1
fi

# Display certificate information
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}   Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}✓ SSL/TLS certificate installed${NC}"
echo -e "${GREEN}✓ Auto-renewal configured${NC}"
echo -e "${GREEN}✓ Nginx configured${NC}"
echo ""
echo "Certificate Details:"
certbot certificates

echo ""
echo "Your site should now be accessible at:"
echo "  https://$DOMAIN"
[ "$INCLUDE_WWW" = "y" ] && echo "  https://www.$DOMAIN"
[ "$INCLUDE_API" = "y" ] && echo "  https://api.$DOMAIN"
echo ""
echo "Certificate will auto-renew before expiration."
echo "Check renewal status: certbot renew --dry-run"
echo ""

exit 0

