name: Deploy to EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Placeholder for AWS Login
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-southeast-1

    # Placeholder for ECR Login
    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: Build Backend Docker image
      run: |
        docker build -t dhakacart-backend ./backend
        # docker tag dhakacart-backend:latest ...

    - name: Build Frontend Docker image
      run: |
        docker build -t dhakacart-frontend ./frontend
        # docker tag dhakacart-frontend:latest ...

    # Placeholder for Deploy
    # - name: Update kubeconfig
    #   run: aws eks update-kubeconfig --name dhakacart-cluster --region ap-southeast-1

    # - name: Deploy to EKS
    #   run: |
    #     kubectl apply -f kubernetes/deployments/
    #     kubectl apply -f kubernetes/services/
